const CharacterCheck = {
    BARON_CASTLE: 0,
    BARON_INN: 1,
    DAMCYAN: 2,
    EBLAN_CAVE: 3,
    GIANT_BABIL: 4,
    KAIPO: 5,
    MIST: 6,
    MT_HOBS: 7,
    MT_ORDEALS: 8,
    MYSIDIA: 9,
    TOWER_ZOT: 10,
    WATERWAY: 11,
    DWARF: 12,
    MOON: 13,
};
const KeyItem = {
    BARON_KEY: 0,
    LUCA_KEY: 1,
    MAGMA_KEY: 2,
    TOWER_KEY: 3,
    DARKNESS_CRYSTAL: 4,
    EARTH_CRYSTAL: 5,
    HOOK: 6,
    TWINHARP: 7,
    PACKAGE: 8,
    PAN: 9,
    SANDRUBY: 10,
    RAT_TAIL: 11,
    ADAMANT: 12,
    LEGEND: 13,
    SPOON: 14,
    PINK_TAIL: 15,
    CRYSTAL: 16,
    PASS: 17,
};
const KeyItemCheck = {
    ADAMANT: 0,
    ANTLION: 1,
    BARON_KING: 2,
    BARON_ODIN: 3,
    BARON_INN: 4,
    FABUL_DEFEND: 5,
    FABUL_SYLPH: 6,
    FABUL_PAN: 7,
    MAGNES: 8,
    MIST: 9,
    MT_ORDEALS: 10,
    TOROIA: 12, // These are out of order since IDs were assigned before typos in Toroia's name were fixed.
    TOWER_ZOT: 11,
    DWARF: 13,
    FEY_CHEST: 14,
    FEY_ASURA: 15,
    FEY_LEVIATHAN: 16,
    LOWER_BABIL_BOSS: 17,
    LOWER_BABIL_CANNON: 18,
    SEALED_CAVE: 19,
    SYLPH_CAVE: 20,
    BAHAMUT: 21,
    MOON_CRYSTAL: 22,
    MOON_MASAMUNE: 23,
    MOON_MURASAME: 24,
    MOON_RIBBON: 25,
    MOON_WHITE: 26,
    HOOK_ROUTE: 27,
    WARP_GLITCH: 28,
};
const Town = {
    AGART: 0,
    BARON: 1,
    EBLAN_CAVE: 2,
    FABUL: 3,
    KAIPO: 4,
    MYSIDIA: 5,
    SILVERA: 6,
    TOROIA_ITEM: 7,
    TOROIA_PUB: 8,
    DWARF: 9,
    FEY: 10,
    TOMRA: 11,
    MOON: 12,
};
const Trap = {
    CASTLE_EBLAN: 0,
    EBLAN_CAVE: 1,
    GIANT_BABIL: 2,
    TOWER_ZOT: 3,
    UPPER_BABIL: 4,
    FEY: 5,
    LOWER_BABIL: 6,
    SYLPH_CAVE: 7,
    MOON_PATH: 8,
    MOON_SUB: 9,
};
Object.freeze(CharacterCheck);
Object.freeze(KeyItem);
Object.freeze(KeyItemCheck);
Object.freeze(Town);
Object.freeze(Trap);